server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: NON_NULL
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: Asia/Shanghai
  # 本地环境
  datasource:
    dynamic:
      primary: primary
      lazy: true
      datasource:
        primary:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/primary?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
          username: root
          password: root
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://mysql://localhost:3306/slave?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
          username: root
          password: root
    # 参数配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    table: flyway_schema_history
    enabled: true
    out-of-order: true
    url: ${spring.datasource.dynamic.datasource.primary.url}
    user: ${spring.datasource.dynamic.datasource.primary.username}
    password: ${spring.datasource.dynamic.datasource.primary.password}
    placeholder-replacement: false
    baselineOnMigrate: true
#redis
redis:
  host: localhost
  port: 6379
  timeout: 200
  max-idle: 200
  min-idle: 50
  max-wait-millis: 1000

logging:
  level:
    ROOT: DEBUG
    org.springframework: INFO
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    org.apache: INFO
    org.mongodb.driver: INFO